version: '3.5'

networks:
  localdev:
    name: localdev
    
services: 
  main-api:
    build: TweetBook/
    restart: always
    ports:
      - "7000:80"
    depends_on: 
      - db-server
    networks: 
      - localdev
  
  db-server:
    image: postgres:latest
    environment:
      - POSTGRES_NAME=tutorial
      - POSTGRES_PASSWORD=Tudor123
      - POSTGRES_DB=TweetBook
    ports:
      - "5432:5432"
    networks: 
      - localdev